<?php

return [
    'Birthday' => '',
    'Birthday Display' => '',
    'How your birthday is displayed on your profile.' => '',
    'Day & Month' => '',
    'Day, Month & Year' => '',
    'Hidden' => '',
    'Category' => '',
    'Confirm Email' => '',
    'Confirm New Password' => '',
    'Confirm Password' => '',
    'Content' => '',
    'Current Password' => '',
    'Email' => '',
    'Hide Alerts Toast?' => '',
    'Stop showing a toast when there is a new alert.' => '',
    'Hide Follows?' => '',
    'Hide your follows and following count.' => '',
    'New Password' => '',
    'Password' => '',
    'Remember Me?' => '',
    'Show Alerts?' => '',
    'Show the alerts dropdown on the topbar.' => '',
    'Show Bookmarks?' => '',
    'Show the bookmarks dropdown on the topbar.' => '',
    'Show Forums Signatures?' => '',
    'Show a users signature under their post.' => '',
    'Show Mail?' => '',
    'Show the mail dropdown on the topbar.' => '',
    'Show Simple Forums?' => '',
    'Show plain text posts by removing any html.' => '',
    'Signature' => '',
    'Status' => '',
    'Subscribe to :resource?' => '',
    'Title' => '',
    'Token' => '',
    'Username' => '',

    'Add' => '',
    'Create :resource' => '',
    'Delete' => '',
    'Discard' => '',
    'Edit' => '',
    'Post a :resource' => '',
    'Restore' => '',
    'Save' => '',
    'Save Changes' => '',
    'Search...' => '',
    'Submit' => '',

    'Character Count: :count/:max' => '',
];
